services:
  - type: web
    runtime: node
    name: crud-app-backend
    rootDir: backend
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: https://showlittlemercy.github.io/CRUD-APPLICATION/
      # other envVars...
