services:
  - type: web
    runtime: node           # for your backend
    name: crud-app-backend
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: https://showlittlemercy.github.io/CRUD-APPLICATION/
  - type: web
    runtime: static         # if your frontend is a plain HTML/CSS/JS static site
    name: crud-app-frontend
    rootDir: frontend
    buildCommand: ""        # no build if plain HTML/CSS/JS
    staticPublishPath: .
    plan: starter

